name: TownyChat
main: com.palmergames.bukkit.TownyChat.Chat
version: 0.22
author: ElgarL, Shade, phrstbrn
website: http://code.google.com/a/eclipselabs.org/p/towny/
description: >
    TownyChat plugin which hooks Towny.

softdepend: [Towny]

commands:
    townychat:
        aliases: []
        usage: /townychat reload
        permission: townychat.reload
